x-proxyconf:
  url: https://localhost:8443/downstream-tls
  listener:
    address: 127.0.0.1
    port: 8443
  security:
    auth:
      downstream: disabled

openapi: 3.0.3
info:
  title: ProxyConf Showcasing different Routing Scenarios using Downstream TLS
  version: 0.1.0
servers:
  - url: http://127.0.0.1:4040/echo
paths:
  /test:
    get:
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              example: '{"hello":"world"}'
              schema:
                type: object
    post:
      requestBody:
        required: true
        content:
          application/json: {}
      responses:
        '200':
          description: "OK"
          content:
            application/json: {}
          
          
