x-proxyconf:
  url: http://localhost:8080/jwt
  security:
    auth:
      downstream:
        type: jwt
        provider-config:
          issuer: localjwtprovider
          audiences: 
            - hurl-tester
          remote_jwks:
            http_uri:
              uri: http://127.0.0.1:4040/local-jwt-provider/jwks.json
              timeout: 1s
            cache_duration:
              seconds: 300
openapi: 3.0.3
info:
  title: ProxyConf Example with JWT Authentication
  version: 0.1.0
servers:
  - url: http://127.0.0.1:4040/echo
paths:
  /test:
    get:
      responses:
        '200':
          description: "OK"
