x-proxyconf-downstream-auth:
  auth_type: header
  config:
    name: my-api-key
    clients:
      testUser:
        # md5sum of supersecret
        - 9a618248b64db62d15b300a07b00580b
x-proxyconf-api-url: http://localhost:8080/demo
x-proxyconf-listener:
  address: 0.0.0.0
  port: 8080
  allowed_source_ips: 
    - 172.18.0.0/16

servers:
  - url: http://127.0.0.1
openapi: 3.1.0
paths:
  /test:
    get:
      responses:
        '200':
          content:
            application/json:
              example: '{"hello":"world"}'
              schema:
                type: object
