name: Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  cli-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - run: nix develop --impure --command -- run-release cli
      - name: Create Checksum
        run: |
          cd ./cli/burrito_out
          chmod +x ./*
          shasum -a 256 ./* > proxyconf_cli_checksums.txt
          cd ..
      - name: Set release details
        id: set_release
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            gh release create ${{ github.ref_name }} --draft=true --latest=true --generate-notes ./cli/burrito_out/*
          else
            gh release delete latest --yes > /dev/null 2>&1
            gh release create ${{ github.ref_name }} --latest=true --generate-notes ./cli/burrito_out/*
          fi
          echo "done"

  image-build:
    name: Build ProxyConf ControlPlane Container Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./control_plane/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
